spring.application.name=job-application-tracker
server.servlet.context-path=/
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/job_application_tracker
spring.datasource.username=postgres
spring.datasource.password=1979
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Logging
logging.level.com.jobtracker=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.flywaydb=DEBUG


#Jwt
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#Endpoints
end.points.auth=/auth
end.points.register=/register
end.points.login=/login

#Swagger
springdoc.api-docs.path=/v3/api-docs
